### ISSUE TITLE
Number of respondents is calculating # of responses, not # of respondents

### ISSUE THREAD

**Issue by thinkcollege** [communityinclusion/escoach#118]
@mgcobblestone 
 This is an issue where we gave you unclear or mistaken instructions.  The # of respondents row in the Activities table on the dashboard is currently outputting the number of responses,not the number of respondents.
 This should be outputting the distinct number of respondents (individuals) in a provider, state, or All that responded to a survey at least once in a month and, had at least one response where they weren't out of office.   Here is the db query that has worked for me:
 For a provider:
` select count(distinct(fullname) ),count(distinct(case when mailer.Complete =1 then fullname end) ) 'total completed including out of office' ,  count(distinct( case when results.answer482 != 11760 then mailer.fullname end)) 'not out of office' from surveycampaign_mailer mailer LEFT JOIN surveycampaign_results results on mailer.contactid = results.contact_id where mailer.surveyid = 5420562 AND mailer.senddate >= '2023-12-01 00:00:00' AND mailer.senddate <= '2023-12-31 23:00:00'  AND results.provider = 'Accord'
 `
 and for All:
 
` select count(distinct(fullname) ),count(distinct(case when mailer.Complete =1 then fullname end) ) 'total completed including out of office' ,  count(distinct( case when results.answer482 != 11760 then mailer.fullname end)) 'not out of office' from surveycampaign_mailer mailer LEFT JOIN surveycampaign_results results on mailer.contactid = results.contact_id where mailer.surveyid = 5420562 AND mailer.senddate >= '2023-12-01 00:00:00' AND mailer.senddate <= '2023-12-31 23:00:00' `
In all cases, when calculating number of respondents this is what we want to use.
cc: @ultimike

**Comment by mgcobblestone** [comment]
Hi @thinkcollege ,
I have pushed an update that should address this issue.

cc: @ultimike

**Comment by thinkcollege** [comment]
Hi @mgcobblestone  This is looking better.  But the # of Respondents row is showing a 1 in the "Me" column, and the warning icon.  The Me column will always be a 1 so it doesn't make any sense to show a number there.  Just leave that empty.
cc: @ultimike

**Comment by mgcobblestone** [comment]
@thinkcollege I've pushed an update for this.

cc: @ultimike

**Comment by thinkcollege** [comment]
@mgcobblestone 
    In the provider csv download (from the admin side, Reports/Provider CSV Download) the number of respondents is still not correct, still too high, but it looks alright at the dashboard level and in the report downloaded on the front end by survey participants. The spreadsheet still includes a number way too high to actually be indicating the number of respondents from that provider.
cc: @ultimike

**Comment by thinkcollege** [comment]
@mgcobblestone @ultimike  Any fixes for this?

**Comment by mgcobblestone** [comment]
@thinkcollege I have pushed up a fix for this.

cc: @ultimike

**Comment by mgcobblestone** [comment]
Hi @thinkcollege , I'm not sure why you re-assigned this to me.  Is there an issue with the fix that was pushed?

cc: @ultimike

**Comment by thinkcollege** [comment]
I don't know how that happened.  I may have been in the wrong issue.

**Comment by thinkcollege** [comment]
My "team" is driving me crazy with nitpicking and backtracking.  I am pusing to launch the site and move forward.
