### ISSUE TITLE
Monthly Trends table row starting point

### ISSUE THREAD

**Issue by ultimike** [communityinclusion/escoach#70]
From #58 

> Finally, you probably plan to address it later, but the table should start with the first month of the 12 month period (i.e. September 2020, not January 2021).

@mgcobblestone Can we make this happen easily?

thanks,  
-mike

**Comment by ultimike** [comment]
@mgcobblestone Looks like the query is returning in the proper order now - but we still need to update the template to match 😄 

thanks,  
-mike

**Comment by mgcobblestone** [comment]
@ultimike This is up on devel

**Comment by ultimike** [comment]
@mgcobblestone Looks good so far - I should have mentioned, I'm pretty sure @escoach will want the year as well, so "September, 2020", "October, 2020", etc...

-mike

**Comment by mgcobblestone** [comment]
@ultimike Years are in place now

**Comment by ultimike** [comment]
@mgcobblestone Looks good.

@escoach The year values have been added to the "Monthly Trends" data table: https://rp-escoach.communityinclusion.org/dashboard

Please review and close this ticket if all is good.

thanks,  
-mike

**Comment by escoach** [comment]
@ultimike Two comments:
Small detail, could you make the width of the columns the same? The "My team" columns are wider than the others.

**Comment by ultimike** [comment]
@escoach That's only one comment, by my count 😄 

I've pushed the fix for the column widths up to the rp-escoach site - give it a few minutes for the deployment process to run then take a look.

thanks,  
-mike

**Comment by escoach** [comment]
@ultimike Still not showing equal-width columns (even after clearing my cache). I will try again later.

I noticed that the dev dashboard shows the September 2021 data even though September 2021 is not a complete month. Question: Will this be the case also in the live dashboard? I mean, will the dashboard shows the current month with whatever data are available at any particular time? For example, on October 2 the dashboard shows the October data (2 days). Or will the dashboard on October 2 show only the September data because October is not complete yet?  Just curious.

**Comment by ultimike** [comment]
@thinkcollege Did the deployment process on rp-escoach get stuck? It looks like my latest pushed changes to `devel` aren't there yet.

@mgcobblestone I think the `addMonthlyParams()` method is not calculating the proper date range for monthly trends (see escoach's comment above). It should not include the current month. For example, with today being Oct 2, the date rate should not include October 2021, but should be from Oct 1 2020 - Sept 30, 2021. Make sense?

thanks,  
-mike

**Comment by thinkcollege** [comment]
@ultimike Just did a test push to devel branch and it deployed successfully to the rp-escoach.communityinclusion.org site.  Don't see any problems.

**Comment by ultimike** [comment]
@thinkcollege Thanks.

@escoach I rebuilt caches on rp-escoach and the equal column widths on the Monthly Trends data table are now present.

-mike

**Comment by mgcobblestone** [comment]
> @mgcobblestone I think the `addMonthlyParams()` method is not calculating the proper date range for monthly trends (see escoach's comment above). It should not include the current month. For example, with today being Oct 2, the date rate should not include October 2021, but should be from Oct 1 2020 - Sept 30, 2021. Make sense?

@ultimike I have confirmed that it is calculating the date range correctly on my local.  Is the latest code in place?  Is the date on the machine where the problem is occurring correct?

**Comment by ultimike** [comment]
@mgcobblestone On both my local and https://escoach.ddev.site/dashboard and select the following:

- What: Getting to know a job seeker
- Time frame: Monthly Trends

The resulting data table begins with October 2021 (the current month). It should start with September 2021 (the most recent previously completed month).

-mike

**Comment by mgcobblestone** [comment]
Hi @ultimike ,
Here's what I see with those selections:
![Screenshot 2021-10-06 181424](https://user-images.githubusercontent.com/29606495/136291008-51909cc1-c509-4a74-b5ff-f1b89b24548f.png)

It does begin with October, but 2020.  You are saying it should start with the previous month, Sept. 2021.  Does that mean it should be sorted DESC?

Thanks.

**Comment by escoach** [comment]
@ultimike Thank you. I was confused because our [Google trend tables](https://docs.google.com/spreadsheets/d/1xKtCi2jgxygtJyhGS4qTN7I6rqtiGHx-LpsuW7877lk/edit#gid=1136224461) end with August 2021 (a complete month) whereas https://rp-escoach.communityinclusion.org/dashboard ends with September 2021, which was not a complete month when we were developing the Google tables and testing the math, back in September. 

This difference triggered this question from a colleague: Will the trend tables in the dashboard show the current month with whatever data are available at any particular time? For example, since today is October 8, will the dashboard show the October data (6 days average)? Or will the dashboard show the last **complete month** i.e. September because October is not complete yet? Just curious.

**Comment by ultimike** [comment]
I believe we're all done here.

-mike

**Comment by thinkcollege** [comment]
Okay
