### ISSUE TITLE
Trends chart

### ISSUE THREAD

**Issue by ultimike** [communityinclusion/escoach#78]
Alberto would like the Trends chart to be a line chart. Example:

![138455991-d046bf12-2080-48bd-8eda-1c0d4e32a0bc](https://user-images.githubusercontent.com/1727889/138472239-2e0713ba-bfda-4d83-85b7-9d219f4017dc.png)

@escoach please provide any other relevant details (colors?)

Google Charts supports line charts so I don't expect it to be too difficult. @mgcobblestone Thoughts?

-mike

**Comment by escoach** [comment]
@ultimike just checking in about the monthly charts. Not sure if they do not show up because of a bug or because you did not have a chance to complete them or if you need anything from me. Here is what I see:
![image](https://user-images.githubusercontent.com/83360935/139707372-8fef9664-24bd-45d5-9ef7-6c098a354a10.png)

Thanks.

**Comment by ultimike** [comment]
@escoach I suspect that this fell through the cracks on @mgcobblestone's to-do list last week 😄 

For the colors - please confirm:

- All - Firebrick
- My team - IndianRed
- Me - DarkOrange

@mgcobblestone Let me know if there's anything else you need from me.

thanks,  
-mike

**Comment by mgcobblestone** [comment]
@ultimike @escoach Sorry, it did fall off the radar.  Will take care of today.

**Comment by escoach** [comment]
@ultimike yes those colors works i.e.:
All - Firebrick
My team - IndianRed
Me - DarkOrange

If it is not too complicated, it would be nice if each line had a different marker. See the example below (Do not pay attention to the colors)

![image](https://user-images.githubusercontent.com/83360935/139852111-c70b91ce-7517-43d3-aa07-7995c0b920fc.png)

**Comment by mgcobblestone** [comment]
@ultimike @escoach I have pushed up an initial version of line charts.  Still a little work to do (like labels in both axes) but this should be enough to start reviewing.

**Comment by escoach** [comment]
@ultimike @mgcobblestone Thank you. Nice start. I hate to ask, but could you replace the colors? My initial choice seemed ok on my end, but I realize that the colors are not distinct enough in the dashboard. Here are [the new colors](https://en.wikipedia.org/wiki/Web_colors#Basic_colors):
•	All: DarkRed
•	My team: Chocolate
•	Me: Gold
I noticed that you added the markers. Thank you.

**Comment by mgcobblestone** [comment]
@escoach It's no problem to change the colors, but to my color-blind eyes, darkred and chocolate are also indistinguishable.  Can I suggest something in the blue family to replace one of those?

**Comment by escoach** [comment]
@mgcobblestone thank you for pointing that out. What about using shades of black-grey like these:
All: Black
My team: Gray
Me: Silver

PS: This [simulator](http://www.color-blindness.com/coblis-color-blindness-simulator/) showed good differentiation among the previous colors, but probably it is not accurate. Not surprised.
The issue with blue is that historically we used blue to identify certain support activities. So, to minimize confusion, we try to stay away from blue unless we talk about those specific activities. But we could consider blue if nothing else works. Thoughts?

**Comment by mgcobblestone** [comment]
@escoach Those work.  I've pushed an update.

**Comment by ultimike** [comment]
Is it just me or is the y-axis non-existent? Or, is this what @mgcobblestone meant by:

> Still a little work to do (like labels in both axes) but this should be enough to start reviewing

-mike

**Comment by escoach** [comment]
I also did not see the axis. Right now there is not even a chart showing up on my screen. I assume that it's a work in progress behind the scene.

**Comment by mgcobblestone** [comment]
@ultimike Correct :-)

I have pushed an update. Now labels are appearing on both axes.  

@escoach Let me know what you would like for the labels of the axes.  I'm not aware of any issues where the chart doesn't display at all, please provide more details on the search that you used.

**Comment by ultimike** [comment]
@mgcobblestone Thanks - looking good on Chrome and Firefox, but there's an issue on Safari (chart doesn't appear).

Also - can you look into the PHP notices in the report log - we should probably clean those up as well.

Regarding Safari - I'm seeing the following error in the browser console when browsing on the rp-escoach site: `Uncaught (in promise) Error: Row 1 has 4 columns, but must have 5` - but I'm also seeing it in Firefox and Chrome (where things are working), so I'm not sure if it's the cause of the problem. 

**But, it works on my local environment, using Safari. ☹️** 

Did some Googling - seems like this might be a common issue. See https://groups.google.com/g/google-visualization-api/c/b1hqa2mcjIA

**Comment by escoach** [comment]
@ultimike @mgcobblestone 

- Now the chart is visible. Looks great.
- The vertical axis label looks good. I would delete the horizontal label "period". It is unnecessary.
- Would it be possible to drop the decimals of the numbers that appear when hovering over the markers on the lines?For example, instead of seeing 55.752 on the first marker, users would see 55.

**Comment by mgcobblestone** [comment]
Hi @ultimike @escoach Fix is in place for the issue that Mike reported (has 4 columns but must be 5).  I have also addressed the items that @escoach requested - no label for h-axis, rounded numbers to ints.

**Comment by ultimike** [comment]
@mgcobblestone Javascript console error is now gone (the "4 columns instead of 5" stuff), and I see the changes to the horizontal axis and rounding. 

I'm still seeing some PHP notices of the form `Notice: Undefined offset: 1 in Drupal\survey_dashboard\Service\QueryBuilder->abbreviateMonth() (line 268 of /var/www/html/web/modules/custom/survey_dashboard/src/Service/QueryBuilder.php)` in the Drupal report log. Any chance those are easy wins?

thanks,  
-mike

**Comment by mgcobblestone** [comment]
@ultimike Notices should be fixed now.

**Comment by ultimike** [comment]
@mgcobblestone The "undefined offset" PHP notices look fixed on my local - rp-escoach isn't responding currently, so I think that @thinkcollege is monkeying around in it...

@mgcobblestone Are you seeing PHP errors on your local (in the report log) similar to `Symfony\Component\HttpKernel\Exception\BadRequestHttpException: Invalid contextual ID specified. in Drupal\contextual\ContextualController->render() (line 76 of /var/www/html/web/core/modules/contextual/src/ContextualController.php).`? Any idea what those are about?

-mike

**Comment by mgcobblestone** [comment]
@ultimike I am not seeing those errors.  I am seeing a couple of notices that I don't think are related to this module:

`Notice: Trying to access array offset on value of type bool in Drupal\webprofiler\DataCollector\RequestDataCollector->collect() (line 47 of /var/www/html/web/modules/contrib/devel/webprofiler/src/DataCollector/RequestDataCollector.php)`

**Comment by ultimike** [comment]
@mgcobblestone Actually, "webprofiler" is the thing that comes with Devel module, so we don't have to worry about that one. 

On the rp-escoach site, I'm seeing ones like these : https://rp-escoach.communityinclusion.org/admin/reports/dblog/event/1033069

```
Notice: Undefined offset: 1 in Drupal\survey_dashboard\Service\QueryBuilder->abbreviateMonth() (line 268 of /home/ici/escoach.communityinclusion.org/escoach/web/modules/custom/survey_dashboard/src/Service/QueryBuilder.php)
```

If it is easy to clean up, we probably should.

thanks,  
-mike

**Comment by escoach** [comment]
Hi @ultimike Just checking in about the monthly trends and making sure that you are not waiting for anything from me to move forward to make them available on the live site.

**Comment by ultimike** [comment]
@escoach as we've discussed previously, I don't have any control over the live site - that's all in @thinkcollege's ballpark.

@mgcobblestone Any update on the PHP notice thing from above?

thanks,  
-mike

**Comment by mgcobblestone** [comment]
@ultimike The notices in abbreviateMonth should have been addressed in one of the last commits

**Comment by ultimike** [comment]
Roger that.

thanks,  
-mike

**Comment by ultimike** [comment]
@thinkcollege @escoach Please confirm that we're all done here.

thanks,  
-mike

**Comment by thinkcollege** [comment]
Okay
